### ISSUE TITLE
numpy dependency is a bit too new, maybe

### ISSUE THREAD

**Issue by ri0t** [secretBiology/SecretColors#4]
I'm having trouble installing SecretColors as dependency on Debian stable (buster) systems, as these only have python3-numpy 1.16.

Luckily (i tested) SecretColors doesn't even need that new  of a numpy, so i propose downgrading it to >=1.16.2

Edit: Also, currently newer versions than 1.19.1 are rejected, which would be the case on any newer-than-stable Debian

**Comment by rohitsuratekar** [comment]
Thank you pointing this out. I have removed the `numpy` version from the requirements ( 707dc57 ). In future, I will try to remove complete `numpy` dependence from the library as only feature used was random number generator and random choices. Please upgrade to the latest version and try again :)

**Comment by ri0t** [comment]
You have a PR for that now, as numpy exploded in my face one time too many, once again ;D

It actually had the brevity of explaining to me that i'd done something wrong.
