### ISSUE TITLE
Material design accent colors?

### ISSUE THREAD

**Issue by fzyzcjy** [secretBiology/SecretColors#6]
Hi thanks for the lib! However, there only seems to be material design normal colors, no accent colors

**Comment by rohitsuratekar** [comment]
Thanks, @fzyzcjy. Accent colors were not available for many color palettes used, hence I decided to exclude them. This also maintained the uniformity across all palettes (with respect to design library design). However, I will try to support the accent colors without disturbing the existing design and will update you :)

**Comment by fzyzcjy** [comment]
@rohitsuratekar Looking forward to the update!

**Comment by rohitsuratekar** [comment]
@fzyzcjy I just [pushed](https://github.com/secretBiology/SecretColors/commit/5b4628bbc73535bc41e5206f1781a3a552367a34) new version `1.2.5` with `material-accent` as a new palette. You can use it just like regular palette. As usual, you can get all material accent colors present on the official [website](https://material.io/design/color/the-color-system.html#tools-for-picking-colors) and for those colors where accent color is not available, it will fall back on available color from other palettes as described [here](https://secretcolors.readthedocs.io/en/latest/api.html#palette). Following is a simple use case, 

```
from SecretColors import Palette
palette = Palette("material-accent")
palette.red()  # Accent Red #FF5252
palette.red(shade=70)  # Accent Red #D50000
```
Give it a try. Please report bugs (if any) :) I hope this helps.

**Comment by fzyzcjy** [comment]
Thanks!
